# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-27 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='linSystemUser',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False, verbose_name='用户id')),
                ('userName', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('userPic', models.ImageField(default='defaultTou.png', upload_to='./%Y/%m%d/', verbose_name='用户头像')),
                ('jurisdiction', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=1, verbose_name='权限等级')),
                ('status', models.IntegerField(choices=[(0, 0), (1, 1)], default=1, verbose_name='用户状态')),
                ('remarks', models.CharField(max_length=10, verbose_name='备注')),
            ],
            options={
                'verbose_name': 'linSystem用户',
                'verbose_name_plural': 'linSystem用户',
                'db_table': '',
                'ordering': ['-userId'],
            },
        ),
    ]
