# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-27 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20200927_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linsystemuser',
            name='remarks',
            field=models.CharField(max_length=10, null=True, verbose_name='备注'),
        ),
    ]
