# Generated by Django 3.1.1 on 2020-10-01 05:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_auto_20200927_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='linSystemNotice',
            fields=[
                ('linSystemNoticeId', models.AutoField(primary_key=True, serialize=False, verbose_name='通知id')),
                ('msg', models.TextField(max_length=200, verbose_name='通知内容')),
                ('status', models.IntegerField(choices=[(0, 0), (1, 1)], default=0, verbose_name='通知状态')),
                ('courseEvaluateDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='通知时间')),
                ('byPerson', models.CharField(default='lin', max_length=10, verbose_name='发布通知者')),
                ('hutNoticeUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.linsystemuser', verbose_name='通知人')),
            ],
            options={
                'verbose_name': 'linSystem通知',
                'verbose_name_plural': 'linSystem通知',
                'db_table': 'linSystem通知',
            },
        ),
    ]
