# Generated by Django 3.1.1 on 2020-10-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_linsystemnotice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linsystemuser',
            name='userPic',
            field=models.ImageField(default='./linSystem/defaultTou.png', upload_to='./linSystem/%Y/%m%d/', verbose_name='用户头像'),
        ),
    ]
