# Generated by Django 3.1.1 on 2020-10-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_auto_20201001_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linsystemuser',
            name='userPic',
            field=models.ImageField(default='/linSystem/defaultTou.png', upload_to='./linSystem/%Y/%m%d/', verbose_name='linSystemUser头像'),
        ),
    ]
