# Generated by Django 3.1.1 on 2020-10-02 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_auto_20201001_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linsystemnotice',
            old_name='hutNoticeUser',
            new_name='linSystemNoticeUser',
        ),
    ]
