# Generated by Django 3.1.1 on 2020-10-12 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_customers_machines_machtypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='gateways_all',
            fields=[
                ('gatewayId', models.AutoField(primary_key=True, serialize=False, verbose_name='网关Id')),
                ('gatewayName', models.CharField(max_length=30, unique=True, verbose_name='网关名')),
            ],
            options={
                'verbose_name': '所有网关',
                'verbose_name_plural': '所有网关',
                'db_table': '所有网关',
                'ordering': ['gatewayId'],
            },
        ),
        migrations.CreateModel(
            name='IOPoints_all',
            fields=[
                ('IOPId', models.AutoField(primary_key=True, serialize=False, verbose_name='监测点')),
                ('IOPName', models.CharField(max_length=30, unique=True, verbose_name='监测点名')),
            ],
            options={
                'verbose_name': '所有监测点',
                'verbose_name_plural': '所有监测点',
                'db_table': '所有监测点',
                'ordering': ['IOPId'],
            },
        ),
        migrations.CreateModel(
            name='IOPoints',
            fields=[
                ('IOPointsId', models.AutoField(primary_key=True, serialize=False, verbose_name='机器监测点id')),
                ('physicalName', models.CharField(max_length=16, unique=True, verbose_name='机器监测点物理名称')),
                ('minRange', models.IntegerField(blank=True, default=0, null=True, verbose_name='最小量程')),
                ('maxRange', models.IntegerField(verbose_name='最大量程')),
                ('aline', models.IntegerField(blank=True, null=True, verbose_name='校准值')),
                ('method', models.IntegerField(blank=True, default=1, null=True, verbose_name='计算方式')),
                ('machineGateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.gateways_all', verbose_name='网关')),
                ('machineName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.machines', verbose_name='机器名')),
            ],
            options={
                'verbose_name': '所有机器监测点',
                'verbose_name_plural': '所有机器监测点',
                'db_table': '所有机器监测点',
                'ordering': ['IOPointsId'],
            },
        ),
        migrations.AddField(
            model_name='gateways_all',
            name='IOPNames',
            field=models.ManyToManyField(related_name='iopname', to='app01.IOPoints_all', verbose_name='监测点名'),
        ),
    ]
