# Generated by Django 3.1.1 on 2020-10-12 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_auto_20201012_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gateways_all',
            name='IOPNames',
        ),
        migrations.DeleteModel(
            name='IOPoints_all',
        ),
    ]
