# Generated by Django 3.1.1 on 2020-10-14 16:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0017_alarmcodes_alarmsolutons'),
    ]

    operations = [
        migrations.CreateModel(
            name='alarmProcessHistory',
            fields=[
                ('alarmProcessHistoryId', models.AutoField(primary_key=True, serialize=False, verbose_name='异常处理历史id')),
                ('alarmCode', models.CharField(blank=True, max_length=16, null=True, verbose_name='异常码编号')),
                ('alarmCodeName', models.CharField(blank=True, max_length=16, null=True, verbose_name='异常码名称')),
                ('alarmSolutonId', models.CharField(blank=True, max_length=32, null=True, verbose_name='解决方案编号')),
                ('callbackMsg', models.TextField(blank=True, null=True, verbose_name='反馈信息')),
                ('processTime', models.DateTimeField(auto_now_add=True, verbose_name='处理时间')),
                ('machineName', models.CharField(blank=True, max_length=16, null=True, verbose_name='机器名称')),
            ],
            options={
                'verbose_name': '异常处理历史',
                'verbose_name_plural': '异常处理历史',
                'db_table': '异常处理历史',
                'ordering': ['alarmProcessHistoryId'],
            },
        ),
        migrations.CreateModel(
            name='singleAlarmCodes',
            fields=[
                ('singleAlarmCodeId', models.AutoField(primary_key=True, serialize=False, verbose_name='单个异常记录id')),
                ('startTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('duration', models.IntegerField(blank=True, default=10, null=True, verbose_name='持续时间')),
                ('singleAlarmCodeStatus', models.IntegerField(default=0, verbose_name='异常记录状态')),
                ('alarmCodeName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.alarmcodes', verbose_name='异常码名字')),
                ('machineName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.machines', verbose_name='机器名')),
            ],
            options={
                'verbose_name': '单个异常记录',
                'verbose_name_plural': '单个异常记录',
                'db_table': '单个异常记录',
                'ordering': ['singleAlarmCodeId'],
            },
        ),
    ]
