# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-22 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0018_alarmprocesshistory_singlealarmcodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='mapPoint',
            fields=[
                ('mapPointId', models.AutoField(primary_key=True, serialize=False, verbose_name='地图标点id')),
                ('mapPointName', models.CharField(max_length=20, unique=True, verbose_name='地图标点名')),
                ('mapPointJ', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='经度')),
                ('mapPointW', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='纬度')),
                ('mapPointAddr', models.CharField(blank=True, max_length=60, null=True, verbose_name='地址')),
                ('mapPointTel', models.CharField(blank=True, max_length=12, null=True, verbose_name='联系电话')),
                ('mapPointBedNum', models.IntegerField(blank=True, null=True, verbose_name='床位')),
                ('mapPointFee', models.IntegerField(blank=True, null=True, verbose_name='费用')),
                ('mapPointJian', models.TextField(blank=True, max_length=150, null=True, verbose_name='简介')),
                ('mapPointServer', models.TextField(blank=True, max_length=300, null=True, verbose_name='服务详情')),
                ('mapPointfare', models.IntegerField(default=0, verbose_name='热度')),
                ('mapPointViews', models.IntegerField(default=0, verbose_name='浏览量')),
            ],
            options={
                'verbose_name': 'linSystem地图项目机构',
                'verbose_name_plural': 'linSystem地图项目机构',
                'db_table': 'linSystem地图项目机构',
                'ordering': ['-mapPointfare'],
            },
        ),
        migrations.CreateModel(
            name='mapPointImages',
            fields=[
                ('mapPointImagesId', models.AutoField(primary_key=True, serialize=False, verbose_name='地图标点图片id')),
                ('mapPointImage', models.ImageField(default='mapPoint/defaultTou.png', upload_to='mapPoint/%Y/%m%d/', verbose_name='地图标点图片')),
                ('mapPoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapPointImages', to='app01.mapPoint', verbose_name='对应标点')),
            ],
            options={
                'verbose_name': 'linSystem地图项目机构图片',
                'verbose_name_plural': 'linSystem地图项目机构图片',
                'db_table': 'linSystem地图项目机构图片',
                'ordering': ['-mapPointImagesId'],
            },
        ),
        migrations.CreateModel(
            name='mapPointVedios',
            fields=[
                ('mapPointVediosId', models.AutoField(primary_key=True, serialize=False, verbose_name='地图标点视频id')),
                ('mapPointVedio', models.FileField(default='mapPointVedio/lin0.mp4', upload_to='mapPointVedio/%Y/%m%d/', verbose_name='地图标点视频')),
                ('mapPoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapPointVedio', to='app01.mapPoint', verbose_name='对应标点')),
            ],
            options={
                'verbose_name': 'linSystem地图项目机构视频',
                'verbose_name_plural': 'linSystem地图项目机构视频',
                'db_table': 'linSystem地图项目机构视频',
                'ordering': ['-mapPointVediosId'],
            },
        ),
    ]
