# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-22 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0019_mappoint_mappointimages_mappointvedios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappointimages',
            name='mapPoint',
        ),
        migrations.RemoveField(
            model_name='mappointvedios',
            name='mapPoint',
        ),
        migrations.DeleteModel(
            name='mapPoint',
        ),
        migrations.DeleteModel(
            name='mapPointImages',
        ),
        migrations.DeleteModel(
            name='mapPointVedios',
        ),
    ]
